DROP DATABASE IF EXISTS IssueTracker;

CREATE DATABASE IssueTracker;

USE IssueTracker;

CREATE TABLE Project (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  Description VARCHAR(255) NULL
);

CREATE TABLE ProjectUser (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Name VARCHAR(255) NOT NULL
);

CREATE TABLE ProjectHasUser (
  UserId INT NOT NULL FOREIGN KEY REFERENCES ProjectUser(Id),
  ProjectId INT NOT NULL FOREIGN KEY REFERENCES Project(Id),
  CONSTRAINT PK_ProjectHasUser PRIMARY KEY (UserId, ProjectId)
);

CREATE TABLE Color (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  HexCode VARCHAR(6) NOT NULL
);

CREATE TABLE Label (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  ProjectId INT NOT NULL FOREIGN KEY REFERENCES Project(Id),
  ColorId INT NOT NULL FOREIGN KEY REFERENCES Color(Id),
  Name VARCHAR(255) NOT NULL
);

CREATE TABLE Issue (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  ProjectId INT NOT NULL FOREIGN KEY REFERENCES Project(Id),
  UserId INT NOT NULL FOREIGN KEY REFERENCES ProjectUser(Id),
  Created DATETIME2 DEFAULT GETDATE() NOT NULL,
  Title VARCHAR(255) NOT NULL,
  Description VARCHAR(255) NOT NULL,
  IsOpen BIT NOT NULL DEFAULT 0
);

CREATE TABLE IssueHasLabel (
  IssueId INT NOT NULL FOREIGN KEY REFERENCES Issue(Id),
  LabelId INT NOT NULL FOREIGN KEY REFERENCES Label(Id),
  CONSTRAINT PK_IssueHasLabel PRIMARY KEY (IssueId, LabelId)
);

CREATE TABLE Comment (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Created DATETIME2 DEFAULT GETDATE() NOT NULL,
  Text VARCHAR(255) NOT NULL,
  UserId INT NOT NULL FOREIGN KEY REFERENCES ProjectUser(Id),
  IssueId INT NOT NULL FOREIGN KEY REFERENCES Issue(Id),
);
