USE PetHospital;
ALTER TABLE TreatmentPrice
  ADD 
	BeginDate DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL DEFAULT SYSUTCDATETIME(),
	EndDate DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),
	PERIOD FOR SYSTEM_TIME (BeginDate, EndDate);

ALTER TABLE TreatmentPrice
  SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.TreatmentPriceHistory));
GO