version: "3.8"

services:
    mssql:
        image: mcr.microsoft.com/mssql/server:latest
        ports:
            - 1433:1433
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Jesp209i # Choose a better password
        volumes: 
            - dbdata:/var/opt/mssql
volumes: 
    dbdata:
