CREATE DATABASE PetHospital
USE PetHospital;

CREATE TABLE Owner(
  Id INT PRIMARY KEY IDENTITY(1,1),
  FirstName VARCHAR(255) NOT NULL,
  Lastname VARCHAR(255) NOT NULL,
  Street VARCHAR(255) NOT NULL,
  PostCode VARCHAR(4) NOT NULL,
  City VARCHAR(255) NOT NULL
);

CREATE TABLE PetType (
  Id INT PRIMARY KEY IDENTITY(1,1),
  TypeName VARCHAR(255) NOT NULL,
);

CREATE TABLE Pet (
  Id INT PRIMARY KEY IDENTITY(1,1),
  Name VARCHAR(255) NOT NULL,
  DateOfBirth DATETIME NOT NULL,
  PetTypeId INT NOT NULL FOREIGN KEY REFERENCES PetType(Id),
  OwnerId INT NOT NULL FOREIGN KEY REFERENCES Owner(Id)
);

CREATE TABLE Invoice(
  Id INT PRIMARY KEY IDENTITY(1,1),
  Created DATETIME DEFAULT GETDATE() NOT NULL,
  Paid BIT DEFAULT 0 NOT NULL
);


CREATE TABLE Visit(
  Id INT PRIMARY KEY IDENTITY(1,1),
  VisitDate DATETIME DEFAULT GETDATE() NOT NULL,
  PedId INT NOT NULL FOREIGN KEY REFERENCES Pet(Id),
  InvoiceId INT NULL FOREIGN KEY REFERENCES Invoice(Id)
);

CREATE TABLE Treatment(
  Id INT PRIMARY KEY IDENTITY(1,1),
  TreatmentName VARCHAR(255) NOT NULL
);

CREATE TABLE Visit_Treatment(
  VisitId INT NOT NULL FOREIGN KEY REFERENCES Visit(Id),
  TreatmentId INT NOT NULL FOREIGN KEY REFERENCES Treatment(Id),
  CONSTRAINT PK_Visit_Treatment PRIMARY KEY (VisitId, TreatmentId)
);

CREATE TABLE PetType_Treatment_Price(
  PetTypeId INT NOT NULL FOREIGN KEY REFERENCES PetType(Id),
  TreatmentId INT NOT NULL FOREIGN KEY REFERENCES Treatment(Id),
  Price DECIMAL(18,2) DEFAULT 0 NOT NULL
  CONSTRAINT PK_PetType_Treatment_Price PRIMARY KEY (PetTypeId, TreatmentId)
);

/*ALTER TABLE Pet
ADD OwnerId INT NOT NULL FOREIGN KEY REFERENCES Owner(Id)

ALTER TABLE PetType_Treatment_Price
ADD CONSTRAINT FK_PetType_Price FOREIGN KEY (PetTypeId) REFERENCES PetType(Id)

ALTER TABLE PetType_Treatment_Price
ADD CONSTRAINT FK_Treatment_Price FOREIGN KEY (TreatmentId) REFERENCES Treatment(Id)*/